{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "devops-test-api.fullname" . }}-route
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: {{ include "devops-test-api.fullname" . }}-gateway
      namespace: {{ .Release.Namespace }}
  hostnames:
    - {{ .Values.gateway.hostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /health
      backendRefs:
        - name: devops-test-api-devops-test-api
          port: 80
{{- end }}
