apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: devops-test-api-route
  namespace: prod
spec:
  parentRefs:
  - name: external-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: devops-test-api-devops-api
      port: 80
