{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devops-test-api.serviceAccountName" . }}
  labels:
    {{- include "devops-test-api.labels" . | nindent 4 }}
{{- end -}}